import { expect, test, type Page } from './fixtures';
import { mkdir } from 'node:fs/promises';

const HERO = 'LM-KT-BTL-001-BLK-500';
const KEY = 'prismlaunch.demo.v1';
const snapshot = (page: Page) => page.evaluate(key => JSON.parse(localStorage.getItem(key)!), KEY);
async function start(page: Page) {
  await page.goto('/');
  await expect(page.getByRole('button', { name: 'Reset Demo', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: 'Reset Demo', exact: true }).click();
  await expect(page.locator('.state-indicator')).toHaveText('Ready to start');
  await expect(page.locator('.product-table tbody tr')).toHaveCount(10);
  await page.getByRole('button', { name: 'Create Demo Task', exact: true }).click();
  await expect(page.getByTestId('recommendation-1')).toContainText(HERO);
  await expect(page.getByTestId('recommendation-1').locator('.match-score')).toHaveText('94/100');
  await page.getByTestId('recommendation-1').getByRole('button', { name: 'Select SKU', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'FactCard V1', exact: true })).toBeVisible();
}
async function generateAmazon(page: Page) {
  await start(page);
  const before = (await snapshot(page)).v1;
  await page.getByRole('button', { name: 'Analyze Evidence', exact: true }).first().click();
  await expect(page.getByRole('button', { name: 'Analyzing product evidence...' })).toBeVisible();
  await expect(page.locator('.suggested-price>strong')).toHaveText('USD 19.99');
  const after = await snapshot(page);
  expect(after.v1).toEqual(before);
  expect(after.v2.facts.length).toBeGreaterThan(after.v1.facts.length);
  await page.getByRole('button', { name: 'Continue to Listing Studio' }).click();
  await page.getByRole('button', { name: 'Generate Amazon Listing' }).click();
  await expect(page.locator('.listing-copy')).toContainText('100% leakproof');
  await expect(page.locator('.listing-copy')).not.toContainText(/Supplier cost|Declared value|Shipping|Duty|8\.20|3\.10/);
}
async function fixAndPass(page: Page) {
  await page.getByRole('button', { name: 'Continue to Review' }).click();
  await expect(page.getByRole('button', { name: 'Publish', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Run Review', exact: true }).click();
  await expect(page.locator('.risk-issue')).toContainText('R001');
  await expect(page.locator('.risk-issue')).toContainText('No verified evidence supports an absolute leakproof claim.');
  await expect(page.getByRole('button', { name: 'Publish', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Apply Suggested Fix', exact: true }).click();
  await expect(page.locator('.listing-copy')).not.toContainText('100% leakproof');
  await expect(page.getByRole('button', { name: 'Publish', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Run Review', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Review Passed', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Publish', exact: true })).toBeEnabled();
}

test('P0 complete: Amazon risk block, human fix, review, mock publish, CSV, reload and reset', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await mkdir('artifacts', { recursive: true });
  await page.goto('/');
  await expect(page.locator('.product-table tbody tr')).toHaveCount(10);
  await page.screenshot({ path: 'artifacts/materials-desktop.png', fullPage: true });
  await generateAmazon(page);
  await page.locator('.fact-sources summary').click();
  await expect(page.locator('.source-facts')).toContainText('Source: Packaging Image');
  await page.screenshot({ path: 'artifacts/listing-studio.png', fullPage: true });
  await page.getByRole('button', { name: 'Continue to Review' }).click();
  await page.getByRole('button', { name: 'Run Review', exact: true }).click();
  await expect(page.locator('.risk-issue')).toContainText('R001');
  await page.screenshot({ path: 'artifacts/review-blocked.png', fullPage: true });
  await page.reload();
  await expect(page.locator('.risk-issue')).toContainText('R001');
  await expect(page.getByRole('button', { name: 'Publish', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Apply Suggested Fix', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Publish', exact: true })).toBeDisabled();
  await expect(page.locator('.listing-copy')).toContainText('Secure screw-top lid designed for everyday carrying.');
  await page.getByRole('button', { name: 'Run Review', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Review Passed', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Publish', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: 'Publish', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Publishing...' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Amazon Listing Export Ready' })).toBeVisible();
  const downloadEvent = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export Amazon CSV' }).click();
  const download = await downloadEvent;
  expect(download.suggestedFilename()).toContain(HERO);
  await download.saveAs('artifacts/amazon-demo.csv');
  const stream = await download.createReadStream();
  const chunks = []; for await (const chunk of stream!) chunks.push(chunk);
  const csv = Buffer.concat(chunks).toString('utf8');
  expect(csv).toContain('19.99'); expect(csv).toContain(HERO); expect(csv).not.toContain('100% leakproof');
  expect(csv).not.toMatch(/supplier.?cost|declared.?value|shipping|duty/i);
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Amazon Listing Export Ready' })).toBeVisible();
  await page.screenshot({ path: 'artifacts/publish-success.png', fullPage: true });
  const completed = await snapshot(page);
  for (const stage of ['initial', 'materials_ready', 'task_created', 'sku_selected', 'evidence_analyzed', 'pricing_ready', 'listing_generated', 'review_blocked', 'review_passed', 'published']) expect(completed.history).toContain(stage);
  await page.getByRole('button', { name: 'Reset Demo', exact: true }).click();
  await expect(page.locator('.product-table tbody tr')).toHaveCount(10);
  expect((await snapshot(page)).task).toBeNull();
  expect((await snapshot(page)).listings).toEqual({});
  expect(errors).toEqual([]);
});

test('missing packaging weight blocks pricing but not selection; duplicates remain excluded', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'View LM-KT-BTL-005-BLK-500', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await expect(dialog.getByRole('heading', { name: 'Pricing Blocked', exact: true })).toBeVisible();
  await expect(dialog).toContainText('Packaging weight is required for logistics estimation.');
  await expect(dialog.locator('.suggested-price')).toHaveCount(0);
  await expect(dialog.getByRole('button', { name: 'Select for Launch' })).toBeVisible();
  await dialog.getByRole('button', { name: 'Close details' }).click();
  await page.getByLabel('Filter materials').selectOption('eligible');
  await expect(page.locator('.product-table tbody tr')).toHaveCount(6);
  await page.getByLabel('Filter materials').selectOption('held');
  await expect(page.locator('.product-table tbody tr')).toHaveCount(4);
  await page.getByRole('button', { name: 'Create Demo Task', exact: true }).click();
  await expect(page.locator('.recommendation-card')).toHaveCount(3);
  await expect(page.locator('.recommendation-grid')).not.toContainText('LM-KT-BTL-007');
  await expect(page.locator('.recommendation-grid')).not.toContainText('LM-KT-BTL-008');
  await expect(page.getByTestId('recommendation-2')).toContainText('LM-KT-BTL-005-BLK-500');
  await expect(page.getByTestId('recommendation-2')).toContainText('No straw');
  await expect(page.getByTestId('recommendation-3')).toContainText('Includes straw');
});

test('Shopify creates a draft independently of the blocked Amazon draft', async ({ page }) => {
  await generateAmazon(page);
  await page.getByRole('button', { name: 'Continue to Review' }).click();
  await page.getByRole('button', { name: 'Run Review', exact: true }).click();
  await expect(page.locator('.risk-issue')).toContainText('R001');
  await page.getByRole('tab', { name: 'Shopify US' }).click();
  await page.getByRole('button', { name: 'Go to Listing Studio' }).click();
  await page.getByRole('button', { name: 'Generate Shopify Listing' }).click();
  await expect(page.locator('.listing-copy')).not.toContainText('100% leakproof');
  await page.getByRole('button', { name: 'Continue to Review' }).click();
  await expect(page.getByRole('button', { name: 'Publish', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Run Review', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Review Passed' })).toBeVisible();
  await page.getByRole('button', { name: 'Publish', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Shopify Draft Created' })).toBeVisible();
  await expect(page.locator('.publish-success')).toContainText('SHOP-DEMO-1042');
  await expect(page.locator('.publish-success')).toContainText('Status: Draft');
  await page.getByRole('tab', { name: 'Amazon US' }).click();
  await expect(page.locator('.risk-issue')).toContainText('R001');
  await expect(page.getByRole('button', { name: 'Publish', exact: true })).toBeDisabled();
});

test('manual edits invalidate review and cannot publish stale approval', async ({ page }) => {
  await generateAmazon(page);
  await fixAndPass(page);
  await page.getByRole('button', { name: 'Edit in Listing Studio' }).click();
  await page.getByRole('button', { name: 'Edit copy' }).click();
  await page.getByRole('textbox', { name: 'Title', exact: true }).fill('FDA certified, guaranteed thermal performance');
  await page.getByRole('button', { name: 'Save revision' }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button', { name: 'Continue to Review' }).click();
  await expect(page.getByRole('button', { name: 'Publish', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Run Review', exact: true }).click();
  await expect(page.locator('.risk-issue')).toContainText('R002');
  await expect(page.getByRole('button', { name: 'Publish', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Apply Suggested Fix' }).click();
  await page.getByRole('button', { name: 'Run Review', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Publish', exact: true })).toBeEnabled();
});

test('mobile layout, source preview keyboard, empty states and invalid storage recovery', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 812 });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.goto('/');
  await expect(page.locator('.product-table tbody tr')).toHaveCount(10);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: 'artifacts/materials-mobile.png', fullPage: true });
  await page.getByRole('navigation', { name: 'Workspaces' }).getByRole('button', { name: 'Review & Publish' }).click();
  await expect(page.getByRole('heading', { name: 'Generate a listing before review' })).toBeVisible();
  await generateAmazon(page);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await fixAndPass(page);
  await page.getByRole('button', { name: 'Publish', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Amazon Listing Export Ready' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: 'artifacts/publish-mobile.png', fullPage: true });
  await page.getByRole('navigation', { name: 'Workspaces' }).getByRole('button', { name: 'Evidence & Facts' }).click();
  await page.getByRole('button', { name: /Supplier Spreadsheet.*View extracted result/ }).click();
  await expect(page.getByRole('dialog')).toContainText('Mock extracted result');
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.evaluate(key => localStorage.setItem(key, '{broken'), KEY);
  await page.reload();
  await expect(page.locator('.product-table tbody tr')).toHaveCount(10);
  expect((await snapshot(page)).selectedSku).toBeNull();
});
