import { useI18n } from '../i18n/I18nContext';
import { useEffect, useState } from 'react';
import { ArrowRight, FileImage, FileSpreadsheet, FileText, ScanLine } from 'lucide-react';
import { useDemo } from '../components/DemoContext';
import { Badge, Button, EmptyState, Modal, NextButton, Notice, PageHeader } from '../components/ui';
import { FactReview } from '../components/FactReview';
import { PricingPanel } from '../components/PricingPanel';
import { mockApi } from '../services/mockApi';
import type { Evidence } from '../types';

export function EvidenceFacts() {
  const { t } = useI18n();
  const { state, busy, act, navigate } = useDemo();
  const [versionsOpen, setVersionsOpen] = useState(() => !state.v2 && state.pricing?.status !== 'blocked');
  const hasV2 = !!state.v2;
  useEffect(() => { if (hasV2) setVersionsOpen(false); }, [hasV2]);
  const [source, setSource] = useState<Evidence | null>(null);
  if (!state.v1 || !state.selectedSku) return <><PageHeader eyebrow={t("03 / EVIDENCE & FACTS")} title={t("Every fact has a source.")} description={t("Keep supplier facts intact. Build a task-specific version from evidence.")} /><EmptyState title={t("Select a product to inspect its evidence")} description={t("Create a launch task and select a recommended SKU to begin.")} action={<NextButton onClick={() => navigate('tasks')}>{t("Go to Launch Tasks")}</NextButton>} /></>;
  const evidence = mockApi.evidence(state.selectedSku);
  const product = state.catalog.find(p => p.sku === state.selectedSku);
  const imported = !!product?.importSource;
  const bag = product?.visual === 'bag';
  return <>
    <PageHeader eyebrow={t("03 / EVIDENCE & FACTS")} title={t("Every fact has a source.")} description={t("Keep supplier facts intact. Build a task-specific version from evidence.")} action={state.v2 ? <div className="evidence-heading-actions"><Button variant="secondary" disabled={!!busy} onClick={() => document.getElementById('fact-review')?.scrollIntoView({ block: 'start' })}>{t("Review Facts")}</Button><NextButton disabled={!!busy} onClick={() => navigate('studio')}>{t("Continue to Listing Studio")}</NextButton></div> : <Button busy={busy === 'analyze'} disabled={!!busy} onClick={() => void act('analyze', () => mockApi.analyzeEvidence(), 'FactCard V2 created. Review the facts before continuing.')}><ScanLine size={16} />{t(busy === 'analyze' ? 'Analyzing product evidence...' : 'Analyze Evidence')}</Button>} />
    {imported && <Notice>{t('Supplier file values and their row references are real imports. Supplemental PDF/image facts and analysis are still mocked; no extra files have been verified.')}</Notice>}
    <div className="evidence-grid">{evidence.map(e => { const Icon = e.type === 'sheet' ? FileSpreadsheet : e.type === 'pdf' ? FileText : FileImage; return <button className="evidence-card" key={e.id} onClick={() => setSource(e)}><div className={`file-icon ${e.type}`}><Icon size={23} /></div><div><strong>{t(e.name)}</strong><span>{e.file}</span><small>{e.id} {t("· View extracted result")} <ArrowRight size={12} /></small></div></button>; })}</div>
      <details className="panel facts-panel" open={versionsOpen} onToggle={event => setVersionsOpen(event.currentTarget.open)}><summary className="fact-version-header"><div><span className="eyebrow">{t("VERSIONED PRODUCT KNOWLEDGE")}</span><h2>{t("FactCard V1")} <ArrowRight size={20} /> <span className={state.v2 ? 'green-text' : 'muted'}>{t("Task-specific FactCard V2")}</span></h2><p>{t('V1 holds supplied base facts. V2 adds task facts without replacing V1; manual changes remain traceable.')}</p></div><Badge tone={state.v2 ? 'green' : 'neutral'}>{t(versionsOpen ? 'Hide version details' : 'View V1 / V2 details')}</Badge></summary><div className="facts-columns"><div className="fact-version"><div className="section-heading"><h3>{t("FactCard V1")}</h3><Badge>{t(state.v1.facts.some(f => f.sourceKind === 'manual') ? 'Base facts · manually reviewed' : 'Original · preserved')}</Badge></div><p className="footnote">{t('Supplier facts · {count} fields', { count: state.v1.facts.length })}</p><dl className="fact-list">{state.v1.facts.map(f => <div key={f.key}><dt>{t(f.label)}</dt><dd>{t(f.value)}</dd></div>)}</dl></div><div className="fact-version v2"><div className="section-heading"><h3>{t("FactCard V2")}</h3><Badge tone={state.v2 ? 'green' : 'neutral'}>{state.v2 ? state.v2.taskId : t('Awaiting analysis')}</Badge></div>{state.v2 ? <><p className="footnote">{t('Inherits {count} V1 fields + 4 evidence fields', { count: state.v1.facts.length })}</p>{state.v2.facts.filter(f => !state.v1!.facts.some(v => v.key === f.key)).map(f => <div className="new-fact" key={f.key}><div><strong>{t(f.label)}</strong><Badge tone={f.allowed ? 'green' : 'amber'}>{t(f.status)}</Badge></div><p>{t(f.value)}</p><small>{t(f.source)} · {t(f.anchor)}</small><Badge tone={f.allowed ? 'green' : 'red'}>{t(f.allowed ? 'Listing Allowed' : 'Not Allowed')}</Badge></div>)}</> : <div className="analysis-empty"><ScanLine size={32} /><h3>{t("Turn evidence into usable facts")}</h3><p>{t(bag ? 'Analyze visible finish, closure and straps. Image-derived facts stay pending until a person confirms them.' : 'Analyze package contents, finish and lid type. Unsupported claims will stay restricted.')}</p><Button variant="secondary" busy={busy === 'analyze'} disabled={!!busy} onClick={() => void act('analyze', () => mockApi.analyzeEvidence(), 'FactCard V2 created. Review the facts before continuing.')}>{t("Analyze Evidence")}</Button></div>}</div></div></details>
    {state.pricing && <PricingPanel pricing={state.pricing} compact />}
    <FactReview />
    <Notice><strong>{t("Evidence, with boundaries.")}</strong> {t(bag ? 'Bag image evidence is mocked. Images may show visible shape, closure and straps, but cannot prove material authenticity, durability or load capacity.' : imported ? 'Supplier rows are imported; supplemental evidence remains mock data. Supplier cost and declared value stay internal. Images cannot establish leakproof performance.' : 'All extraction results are mock data. Images can confirm visible contents and finish; they cannot establish leakproof performance. Supplier cost and declared value remain internal.')}</Notice>
    <Modal open={!!source} onOpenChange={open => !open && setSource(null)} title={t(source?.name ?? 'Evidence')} description={t(source?.name === 'Imported Supplier File' ? 'Parsed supplier values · local file and row reference' : 'Mock extracted result · no OCR or file processing is performed')}>{source && <div className="source-preview"><Badge tone="blue">{source.id}</Badge><h3>{source.file}</h3><p>{source.name === 'Supplier Spreadsheet' ? t('{sku} · Products & Packaging', { sku: state.selectedSku }) : t(source.anchor)}</p><ul>{source.extracted.map(line => <li key={line}>{t(line)}</li>)}</ul><Notice>{t(source.name === 'Imported Supplier File' ? 'These values were parsed from your supplier file. This is a row preview, not independent verification of the supplier claims.' : 'Illustrative evidence only. This preview shows fixed extracted fields, not a downloaded source file.')}</Notice></div>}</Modal>
  </>;
}
