import { colorHex } from '../components/presentation';
import { translate, useI18n } from '../i18n/I18nContext';
import { useState } from 'react';
import { ArrowRight, CheckCheck, Filter, Search } from 'lucide-react';
import { useDemo } from '../components/DemoContext';
import { Badge, Button, Modal, Notice, PageHeader, ProductVisual } from '../components/ui';
import { SupplierImport } from '../components/SupplierImport';
import { ImportReview } from '../components/ImportReview';
import { SourceAssets } from '../components/SourceAssets';
import { PricingPanel } from '../components/PricingPanel';
import { mockApi } from '../services/mockApi';
import { dimensionsFromText, formatCapacity, formatDimensions } from '../../shared/units';
import type { Product } from '../types';

export function Materials() {
  const { t } = useI18n();
  const { state, products, busy, act, navigate } = useDemo();
  const [query, setQuery] = useState(''); const [filter, setFilter] = useState('all');
  const [detail, setDetail] = useState<Product | null>(null);
  const [importToken, setImportToken] = useState(0);
  const eligible = products.filter(mockApi.isEligible).length;
  const filtered = products.filter(p => `${p.sku} ${p.name} ${p.category} ${p.color} ${translate('zh', p.name)} ${translate('zh', p.category)} ${translate('zh', p.color)}`.toLowerCase().includes(query.toLowerCase()) && (filter === 'all' || (filter === 'eligible' ? mockApi.isEligible(p) : !mockApi.isEligible(p))));
  return <>
    <PageHeader eyebrow={t("01 / SUPPLIER WORKSPACE")} title={t("Good launches start with good data.")} description={t("Organize supplier materials. Know what is ready before you recommend.")} action={<Button busy={busy === 'create'} disabled={!!busy} onClick={() => state.task ? navigate('tasks') : void act('create', () => mockApi.createTask(), 'Demo task created. Your Top 3 are ready.')}>{t(state.task ? 'View Launch Task' : 'Create Demo Task')}<ArrowRight size={16} /></Button>} />
    <SupplierImport onDatasetChange={() => { setQuery(''); setFilter('all'); setDetail(null); setImportToken(t => t + 1); }} />
    <ImportReview refreshToken={importToken} />
    <div className="materials-overview"><div className="stats-panel"><div className="stat"><span>{t("Total products")}</span><strong>{products.length.toString().padStart(2, '0')}</strong><small>{t(state.datasetSource === 'builtin' ? 'From one mock supplier' : 'From supplier files')}</small></div><div className="stat"><span>{t("Candidate pool")}</span><strong className="green-text">{eligible.toString().padStart(2, '0')}</strong><small>{t("Ready, unique & in category")}</small></div><div className="stat"><span>{t("Held for review")}</span><strong>{(products.length - eligible).toString().padStart(2, '0')}</strong><small>{t("Incomplete or outside scope")}</small></div></div></div>
    <section className="panel catalog-panel"><div className="catalog-toolbar"><div className="section-heading"><h2>{t("Supplier materials")}</h2><Badge>{products.length} {t("SKUs")}</Badge></div><div className="table-controls"><label className="search-field"><Search size={16} /><input aria-label={t("Search materials")} placeholder={t("Search products or SKU...")} value={query} onChange={e => setQuery(e.target.value)} /></label><label className="filter-field"><Filter size={15} /><select aria-label={t("Filter materials")} value={filter} onChange={e => setFilter(e.target.value)}><option value="all">{t("All materials")}</option><option value="eligible">{t("Candidate pool")}</option><option value="held">{t("Held for review")}</option></select></label></div></div>
    <p className="mobile-table-hint">{t("More columns are available by scrolling this table. Tap a product for full details.")}</p><div className="table-scroll"><table className="product-table"><thead><tr><th>{t("Product / SKU")}</th><th>{t("Category")}</th><th>{t("Color")}</th><th>{t("Key specification")}</th><th>{t("Data status")}</th><th>{t("Duplicate status")}</th><th><span className="sr-only">{t("Details")}</span></th></tr></thead><tbody>{filtered.map(p => <tr key={p.sku} data-testid={`product-${p.sku}`}><td><button className="product-cell" onClick={() => setDetail(p)}><ProductVisual product={p} /><span><strong>{t(p.name)}</strong><code>{p.sku}</code></span></button></td><td>{t(p.category)}</td><td><span className="color-dot" style={{ background: colorHex(p.color), borderColor: colorHex(p.color) }} />{t(p.color)}</td><td>{t(p.visual === 'bag' ? 'Tote bag' : p.visual === 'lamp' ? 'Desk lamp' : p.capacity ? formatCapacity(p.capacity, mockApi.unitSystem()) : '—')}</td><td><Badge tone={p.status === 'search_ready' ? 'green' : 'amber'}>{t(p.status === 'search_ready' ? 'Ready' : 'Missing Data')}</Badge></td><td><Badge tone={p.duplicateStatus === 'unique' ? 'neutral' : p.duplicateStatus === 'duplicate' ? 'red' : 'amber'}>{t(p.duplicateStatus === 'unique' ? 'Unique' : p.duplicateStatus === 'duplicate' ? 'Duplicate' : 'Possible Duplicate')}</Badge></td><td><Button variant="ghost" aria-label={t('View {sku}', { sku: p.sku })} onClick={() => setDetail(p)}><ArrowRight size={16} /></Button></td></tr>)}</tbody></table>{filtered.length === 0 && <div className="table-empty">{t("No products match your search. Try another SKU or filter.")}</div>}</div>
    <div className="table-footer"><span>{t('Showing {shown} of {total} products', { shown: filtered.length, total: products.length })}</span><span><CheckCheck size={14} /> {t(state.datasetSource === 'builtin' ? 'Mock supplier import complete' : 'Supplier file imported')}</span></div></section>

    <Modal open={!!detail} onOpenChange={open => !open && setDetail(null)} title={t(detail?.name ?? 'Product details')} description={t(detail?.sku ?? '')} wide>{detail && <><div className="detail-summary"><ProductVisual product={detail} large /><div><Badge tone={mockApi.isEligible(detail) ? 'green' : 'amber'}>{t(mockApi.isEligible(detail) ? 'Candidate ready' : 'Not in candidate pool')}</Badge><h3>{t(detail.name)}</h3><p>{t(mockApi.exclusionReason(detail))}</p><p>{detail.packagingDimensions ? t('Packaging: {dimensions}', { dimensions: formatDimensions(dimensionsFromText(detail.packagingDimensions), mockApi.unitSystem()) ?? detail.packagingDimensions }) : t('Packaging dimensions: Missing')}</p></div></div><SourceAssets sku={detail.sku} /><div className="fact-table-wrap"><table className="fact-table"><thead><tr><th>{t("FactCard V1 · field")}</th><th>{t("Value")}</th><th>{t("Evidence")}</th></tr></thead><tbody>{mockApi.getFacts(detail.sku).facts.map(f => <tr key={f.key}><td>{t(f.label)}</td><td>{t(f.value)}</td><td>{t(f.source)}</td></tr>)}</tbody></table></div><PricingPanel pricing={mockApi.previewPricing(detail.sku)} compact /><Notice>{t(mockApi.exclusionReason(detail))}</Notice><div className="modal-actions"><Button variant="secondary" disabled={!!busy} onClick={async () => { if (await act('open-facts', () => mockApi.openFactReview(detail.sku), 'Fact Review opened. Missing products can be repaired here.')) setDetail(null); }}>{t('Review Facts')}</Button><Button variant="secondary" onClick={() => setDetail(null)}>{t("Close details")}</Button>{mockApi.isEligible(detail) && <Button disabled={!!busy} onClick={async () => { const sku = detail.sku; const ok = !state.task ? await act('create', () => mockApi.createTask(), 'Demo task created.') : true; if (ok && await act('select', () => mockApi.selectSku(sku), 'Product selected. Explore its evidence.')) setDetail(null); }}>{t("Select for Launch")}<ArrowRight size={16} /></Button>}</div></>}</Modal>
  </>;
}
