import { useI18n } from '../i18n/I18nContext';
import { Check, CheckCircle2, Download, ExternalLink, LockKeyhole, Rocket, ShieldCheck, ShieldX } from 'lucide-react';
import { useDemo } from '../components/DemoContext';
import { ListingPreview } from '../components/ListingPreview';
import { Badge, Button, EmptyState, NextButton, Notice, PageHeader, PlatformTabs } from '../components/ui';
import { mockApi } from '../services/mockApi';

export function ReviewPublish() {
  const { t } = useI18n();
  const { state, busy, act, navigate, setState, notify } = useDemo();
  const listing = state.listings[state.platform]; const review = state.reviews[state.platform]; const publication = state.publications[state.platform];
  const canPublish = mockApi.canPublish();
  const exportCsv = () => {
    try {
      const blob = new Blob([mockApi.exportCsv()], { type: 'text/csv;charset=utf-8;' });
      const url = URL.createObjectURL(blob); const link = document.createElement('a');
      link.href = url; link.download = `PrismLaunch-${state.selectedSku}-Amazon.csv`; document.body.appendChild(link); link.click(); link.remove();
      setTimeout(() => URL.revokeObjectURL(url), 1000); notify('Amazon CSV downloaded.');
    } catch (error) { notify(error instanceof Error ? error.message : 'Export failed.', true); }
  };
  return <><PageHeader eyebrow={t("05 / REVIEW & PUBLISH")} title={t("One final check. A confident launch.")} description={t("Catch unsupported claims, make a human correction, then publish your reviewed revision.")} action={<Badge tone="blue">{t("Mock publish only")}</Badge>} /><div className="studio-toolbar"><PlatformTabs value={state.platform} disabled={!!busy} onChange={p => setState(mockApi.setPlatform(p))} />{listing && <span className="muted">{t('Reviewing revision {revision}', { revision: listing.revision })}</span>}</div>
    {!listing ? <EmptyState title={t("Generate a listing before review")} description={t('There is no {platform} draft for this product yet.', { platform: state.platform === 'amazon' ? 'Amazon' : 'Shopify' })} action={<NextButton onClick={() => navigate('studio')}>{t("Go to Listing Studio")}</NextButton>} /> : <>
      {publication && <section className="publish-success" role="status"><div className="success-symbol"><Check size={30} /></div><div><div className="eyebrow">{t("MOCK PUBLISH SUCCESS")}</div><h2>{t(publication.platform === 'shopify' ? 'Shopify Draft Created' : 'Amazon Listing Export Ready')}</h2><p>{t("Demo Product ID:")} <strong>{publication.productId}</strong><span> {t("· Status:")} <strong>{t(publication.status)}</strong></span></p><p>{t('Revision {revision} passed review. No live marketplace was contacted.', { revision: publication.revision })}</p></div>{publication.platform === 'amazon' ? <Button onClick={exportCsv}><Download size={16} />{t("Export Amazon CSV")}</Button> : <Badge tone="green">{t("Draft")}</Badge>}</section>}
      <div className="review-grid"><div><ListingPreview listing={listing} /><div className="review-edit-link"><Button variant="ghost" disabled={!!busy} onClick={() => navigate('studio')}>{t("Edit in Listing Studio")}<ExternalLink size={14} /></Button></div></div><aside className="review-aside"><section className={`panel review-panel ${review?.status ?? 'pending'}`}><div className="panel-title">{review?.status === 'blocked' ? <ShieldX size={21} /> : <ShieldCheck size={21} />}<h3>{t("Listing review")}</h3><Badge tone={review?.status === 'blocked' ? 'red' : review?.status === 'passed' ? 'green' : 'neutral'}>{t(review?.status === 'blocked' ? 'HIGH RISK' : review?.status === 'passed' ? 'Passed' : 'Not reviewed')}</Badge></div>
      {!review && <div className="review-intro"><h3>{t(listing.revision > 1 ? 'Revision updated. Review again.' : 'Ready for a fact check.')}</h3><p>{t("Check consumer copy against confirmed facts before enabling publication.")}</p></div>}
      {review?.status === 'blocked' && <><div className="risk-count"><strong>{review.issues.length}</strong><span>{t(review.issues.length === 1 ? 'High Risk Issue' : 'High Risk Issues')}<small>{t("Publishing is blocked")}</small></span></div>{review.issues.map(issue => <div className="risk-issue" key={issue.id}><Badge tone="red">{issue.id} {t("· HIGH RISK")}</Badge><h4>{t(issue.title)}</h4><blockquote>{t(issue.text)}</blockquote><p>{t(issue.reason)}</p></div>)}<div className="suggested-fix"><span className="field-label">{t("SUGGESTED FIX")}</span><p lang="en">Secure screw-top lid designed for everyday carrying.</p><small>{t('Supported by {source} · Page 1 · closure. Other edited fields return to confirmed wording.', { source: t(listing.sources.find(f => f.key === 'lidType')?.source ?? 'Specification PDF') })}</small><Button variant="secondary" busy={busy === 'fix'} disabled={!!busy} onClick={() => void act('fix', () => mockApi.applyFix(), 'Suggested fix applied. Run Review again to approve this revision.')}>{t("Apply Suggested Fix")}</Button></div></>}
      {review?.status === 'passed' && <div className="review-passed"><CheckCircle2 size={35} /><h3>{t("Review Passed")}</h3><strong>{t("High Risk Issues: 0")}</strong><p>{t('Revision {revision} uses confirmed, listing-allowed facts. The unsupported claim has been removed.', { revision: review.revision })}</p></div>}
      <Button variant={review?.status === 'passed' ? 'secondary' : 'primary'} busy={busy === 'review'} disabled={!!busy || !!publication} onClick={() => void act('review', () => mockApi.runReview(), 'Review complete. See the result below.')}><ShieldCheck size={16} />{t(busy === 'review' ? 'Reviewing listing...' : 'Run Review')}</Button></section>
      <section className="panel publish-panel"><div className="panel-title"><Rocket size={19} /><h3>{t("Publish destination")}</h3></div><div className="destination"><span className="platform-monogram">{state.platform === 'amazon' ? 'a' : 's'}</span><div><strong>{t(state.platform === 'amazon' ? 'Amazon US' : 'Shopify US')}</strong><small>{t(state.platform === 'amazon' ? 'Mock publish → downloadable CSV' : 'Mock publish → product draft')}</small></div></div><Button disabled={!!busy || !canPublish || !!publication} busy={busy === 'publish'} onClick={() => void act('publish', () => mockApi.publish(), 'Mock Publish Success. Your reviewed listing is ready.')}>{canPublish ? <Rocket size={16} /> : <LockKeyhole size={16} />}{t(busy === 'publish' ? 'Publishing...' : publication ? 'Published' : 'Publish')}</Button>{!canPublish && <p className="footnote">{t(review?.status === 'blocked' ? 'Resolve all high-risk issues and run review again.' : 'A passed review of the current revision is required.')}</p>}{canPublish && !publication && <p className="footnote">{t("Current revision approved · ready to mock publish.")}</p>}</section><Notice>{t("Deterministic mock review, not a compliance certification. Shopify creates a demo draft; Amazon produces a demo CSV, not an uploaded listing.")}</Notice></aside></div>
    </>}
  </>;
}
