import { Sparkles, FileText } from 'lucide-react';
import type { Listing } from '../types';
import { useI18n } from '../i18n/I18nContext';
export function GenerationIndicator({ listing }: { listing: Listing }) {
  const { t } = useI18n();
  const ai = listing.generationMode === 'qwen'; const fallback = listing.generationMode === 'template_fallback';
  return <div className={`generation-indicator ${fallback ? 'generation-fallback' : ''}`} data-testid="generation-indicator">
    {/* The plain template needs no announcement; a model run or a degraded fallback still says so. */}
    {(ai || fallback) && <div className="generation-summary">{ai ? <Sparkles size={16} aria-hidden="true" /> : <FileText size={16} aria-hidden="true" />}<span>{t('Generated by')} <strong>{ai ? `Qwen · ${listing.generation?.model ?? ''}` : t('Template fallback')}</strong></span>{listing.generation?.cacheHit && <span className="generation-cache">{t('Reused saved generation')}</span>}</div>}
    {fallback && <p>{t('AI generation was unavailable or did not pass validation. A template draft is ready; you can continue reviewing.')}</p>}
    {(listing.generation?.promptVersion || listing.riskDemoInjected) && <details><summary>{t('Generation details')}</summary><div className="generation-details">
      {listing.generation?.promptVersion && <span>{t('Prompt version')}: {listing.generation.promptVersion}</span>}
      <span>{t('Facts revision')}: {listing.factRevision ?? 0}</span>
      {listing.riskDemoInjected && <span>{t('Demo risk injection: this claim was added by a demo action, not inferred from authorized facts.')}</span>}
    </div></details>}
  </div>;
}
