import { GenerationIndicator } from './GenerationIndicator';
import { useI18n } from '../i18n/I18nContext';
import { BookOpen, FilePenLine } from 'lucide-react';
import type { Listing } from '../types';
import { Badge, Button } from './ui';

export function ListingPreview({ listing, onEdit, disabled }: { listing: Listing; onEdit?: () => void; disabled?: boolean }) {
  const { t, language } = useI18n();
  return <section className="panel listing-preview"><div className="panel-title"><FilePenLine size={19} /><h3>{t('{platform} listing', { platform: t(listing.platform === 'amazon' ? 'Amazon US' : 'Shopify US') })}</h3><Badge>{t('Revision {revision}', { revision: listing.revision })}</Badge>{onEdit && <Button variant="ghost" onClick={onEdit} disabled={disabled}>{t("Edit copy")}</Button>}</div><GenerationIndicator listing={listing} /><div className="listing-copy">{language === 'zh' && <p className="listing-language-note">{t('US-market listing copy and exports remain in English. Interface language does not change your draft.')}</p>}<div className="copy-section"><span className="field-label">{t("TITLE")}</span><h2 lang="en">{listing.title}</h2></div><details className="fact-sources"><summary><BookOpen size={16} /> {t("Fact Sources")} <Badge>{t('{count} confirmed fields', { count: listing.sources.length })}</Badge></summary><div className="source-facts">{listing.sources.map(f => <div key={f.key}><strong>{t(f.label)}</strong><span>{t("Source:")} {t(f.source)}</span><small>{t(f.anchor)}</small></div>)}</div></details><div className="copy-section"><span className="field-label">{t(listing.platform === 'amazon' ? 'BULLET POINTS' : 'PRODUCT HIGHLIGHTS')}</span><ul className="listing-bullets" lang="en">{listing.bullets.map((bullet, i) => <li key={i}>{/100%\s*leakproof/i.test(bullet) ? <mark>{bullet}</mark> : bullet}</li>)}</ul></div><div className="copy-section"><span className="field-label">{t("DESCRIPTION")}</span><p lang="en">{listing.description}</p></div><div className="copy-section"><span className="field-label">{t("ATTRIBUTES")}</span><dl className="attribute-grid" lang="en">{Object.entries(listing.attributes).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl></div></div></section>;
}
